[package]
name = "mqtt"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
bytes = "1.0"
rand = "0.8"
log = "0.4"
env_logger = "0.9"
async-trait = "0.1"