[package]
name = "SSE-web"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4"
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
parking_lot = "0.12"
tokio-stream = { version = "0.1", features = ["sync"] }
futures-util = "0.3"
