[package]
name = "websocket"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4"
actix-ws = "0.2"
tokio = { version = "1", features = ["full"] }
uuid = { version = "1.4", features = ["v4"] }
chrono = "0.4"