[package]
name = "vue3-websocket"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-util = "0.3.31"
tokio = { version = "1.42.0", features = ["full"] }
tokio-tungstenite = "0.24.0"
tungstenite = "0.24.0"
